server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${SERVER_PORT:8761}/eureka/

  server:
    enable-self-preservation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always