server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway-service
  config:
    import: "optional:file:${ENV_FILE:./.env}[.properties]"

  cloud:
    gateway:
      server:
        webmvc:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: identity-service-auth
              uri: lb://identity-service
              predicates:
                - Path=/api/v1/auth/**

            - id: identity-service-users
              uri: lb://identity-service
              predicates:
                - Path=/api/v1/users/**

            - id: journey-service
              uri: lb://journey-service
              predicates:
                - Path=/api/v1/journey/**

            - id: prayer-service
              uri: lb://prayer-service
              predicates:
                - Path=/api/v1/prayers/**

            - id: quran-service
              uri: lb://quran-service
              predicates:
                - Path=/api/v1/quran/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/notifications/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

  endpoint:
    health:
      show-details: always
